### ISSUE TITLE
Q: Why privileged approach instead of user and compose services?

### ISSUE THREAD

**Issue by LongLiveCHIEF** [postlund/hassio-compose#4]
So, I'm just getting started with HASS, but I'm fairly experienced with all things docker. I was digging around to see if anyone had a good `.gitignore` for a version-controlled docker-compose-ified home assistant setup, and came across your project.

I'm wondering why you need `privileged`?  I've been adding HASS add-ons as `services` in my docker-compose file, and using a yaml anchor to set the `user:` for each service to my local user uid:gid.

Example:

```
version: '3.7'

x-common: &common
  restart: unless-stopped
  user: "${LOCAL_USER}:${LOCAL_USER}"

services:
  <<: *common
  container_hame: hass
  image: homeassistant/home-assistant
```
I'm curious if that was an approach you tried and decided wasn't quite right, so that I can save myself a headache!
